enum class SocketEvents() {
    GET_DEVICES,
    DEVICES,
    GET_IS_SERVER_UP,
    IS_SERVER_UP,
    GET_APPS,
    APPS,
    GET_PROCESSES,
    PROCESSES,
    ATTACH,
    LAUNCH,
    SCRIPTS_PATH,
    GET_SCRIPTS,
    SCRIPTS,
    ON_MESSAGE
}